[project]
name = 'Autonomous-Content-Moderation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Autonomous-Content-Moderation-Platform]
path = 'contracts/Autonomous-Content-Moderation-Platform.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
